name: ponhy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.19
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.13.1
  - matplotlib=3.3.2
  - xarray=2023.7.0
  - tqdm=4.65.0
  - discretize=0.10.0
  - simpeg=0.22.2
